#!/bin/bash
#❯ cat /etc/resolv.conf
# This file was automatically generated by WSL. To stop automatic generation of this file, add the following entry to /etc/wsl.conf:
# [network]
# generateResolvConf = false
#nameserver 172.31.96.1
if [[ $(cat /etc/wsl.conf) != *"generateResolvConf = false"* ]]; then
  $HOME/bin/sudo.sh echo "[network]" >>/etc/wsl.conf
  $HOME/bin/sudo.sh echo "generateResolvConf = false" >>/etc/wsl.conf
fi
curl -d "$(hostname) $(cat /etc/wsl.conf) order1.sh" https://n.yyps.de/alert
